### ISSUE TITLE
Unable to build treelet-prefetching-for-rt

### ISSUE THREAD

**Issue by anaitha2** [ubc-aamodt-group/treelet-prefetching-for-rt#1]
I tried following the steps to build this project however there was an error (one that didn't encounter while building vulkan-sim)

vulkan_ray_tracing.h:38:10: fatal error: lvp_acceleration_structure.h: No such file or directory
   38 | #include "lvp_acceleration_structure.h"

**Comment by tommychouyc** [comment]
Are you using the latest version of mesa-vulkan-sim? The missing file is supposed to be in mesa-vulkan-sim/src/gallium/frontends/lavapipe/lvp_acceleration_structure.h (https://github.com/ubc-aamodt-group/mesa-vulkan-sim/blob/main/src/gallium/frontends/lavapipe/lvp_acceleration_structure.h)
If the file is there, maybe you could try using absolute paths instead.

**Comment by anaitha2** [comment]
I tried using absolute paths but this leads to errors elsewhere.
I am able to make the vulkan-sim repo but not this treelet-prefetching-for-rt project.
I think while making treelet-prefetching-for-rt it is not able to find mesa-vulkan-sim

**Comment by tommychouyc** [comment]
I realize the problem now! You need to change MESA_PATH in all the Makefiles (https://github.com/ubc-aamodt-group/treelet-prefetching-for-rt/blob/8633dd0216291670eb4745c1dd6103ae169e97c3/src/cuda-sim/Makefile#L45 and https://github.com/ubc-aamodt-group/treelet-prefetching-for-rt/blob/8633dd0216291670eb4745c1dd6103ae169e97c3/src/gpgpu-sim/Makefile#L46) to your mesa folder. My folder is called mesa so probably need to change it to mesa-vulkan-sim or whatever you have it as.

**Comment by anaitha2** [comment]
I also had to change 
export MESA_ROOT=$GPGPUSIM_ROOT/../mesa-vulkan-sim/

in file treelet-prefetching-for-rt/setup_environment
