### ISSUE TITLE
Assertion error when running Lumibench with treelet-prefetching-for-rt

### ISSUE THREAD

**Issue by intsoo** [ubc-aamodt-group/treelet-prefetching-for-rt#2]
When running the Lumibench (`RayTracingInVulkan`) by command `./RayTracer --scene 18 --width 128 --height 128 --samples 2`, I encountered an assertion error. _This error did not occur when running the Lumibench with the original Vulkan-Sim (https://github.com/ubc-aamodt-group/vulkan-sim.git)._ 

``` bash
----------------------------END-of-Interconnect-DETAILS-------------------------


gpgpu_simulation_time = 0 days, 0 hrs, 0 min, 21 sec (21 sec)
gpgpu_simulation_rate = 203090 (inst/sec)
gpgpu_simulation_rate = 13204 (cycle/sec)
gpgpu_silicon_slowdown = 103377x
Destroy streams for kernel 1: size 0

RayTracer: ../src/gallium/auxiliary/util/u_surface.c:267: util_resource_copy_region: Assertion `src_bs == dst_bs' failed.
Aborted (core dumped)
```

This is the result when using the gdb.
![image](https://github.com/user-attachments/assets/70497326-0159-4973-9072-5e0e8155ba19)

**Comment by tommychouyc** [comment]
Hi, I'm not sure what causes that as I can't reproduce that error on my end, but as long as you see the gpgpu_simulation_time stats / end of interconnect message, it means that the simulation is complete.

**Comment by intsoo** [comment]
Hi, I solved the issue with the following steps:

**1. Configuration File Differences:** The GPU configuration file (`gpgpusim.config`) that I used for the Treelet Prefetching was different from the one for the original Vulkan-Sim simulation.
- **For Treelet Prefetching** (which caused the assertion error), I used `treelet-prefetching-for-rt/configs/tested-cfgs/MOBILE/gpgpusim.config`. 
- **For the original Vulkan-Sim** (which worked fine), I used the `vulkan-sim/configs/tested-cfgs/MOBILE/gpgpusim.config`.

=> Using the same configuration file from `vulkan-sim/` for Treelet Prefetching resolved the assertion error. _(I'm still unsure what caused the error)_
**_=> Actually, I used the `treelet-prefetching-for-rt/configs/tested-cfgs/treelet_prefetching/*` for the final simulation to enable Treelet Prefetching.._**

**2. Image Generation Issue**: Even after fixing the configuration, the Treelet Prefetching simulation still wasn't generating the output PPM image. I discovered that in the `treelet-prefetching-for-rt/` source, the `writeImageBinary` variable was set to `false`, unlike in the `vulkan-sim/` source. 

=>Changing `writeImageBinary` to `true` successfully generated the image.

**_Thank you for your response!_**

**Comment by jonatso** [comment]
Hello,

I also have similar issues, but for almost all benchmarks. I'm using the Docker image from the lumibench paper, but switched out the source code (and recompiled) to this repo. I use the configs from `treelet-prefetching-for-rt/configs/tested-cfgs/treelet_prefetching/*.`, and use 32x32 resolution with 1 SPP, as done in the paper. I've tried with both PT, SH, and AO, used both the default config (which seems to have the prefething disabled), as well as 
`
-keep_accepting_warps 1
-treelet_prefetch 1
`
to enable the prefetching. I've tried both the RayTracingInVulkan and Mesa code that came with the Lumibench docker image, and updated the source code to the latest releases from Github, with no effect. 

I've had multiple different errors:
For BATH, CRNVL, FOX, FRST, LANDS, PARK, PARTY, REF, SPNZA, (also sometimes with BUNNY, other times it completes...)
RayTracer: ../src/gallium/auxiliary/util/u_surface.c:267: util_resource_copy_region: Assertion `src_bs == dst_bs' failed.
As with @intsoo, this error came with the "END-of-Interconnect-DETAILS", so it is good to hear that the simulations are complete. Looking at BUNNY, i see that runs that ends with the assertion error have identical/simular statistics, which looks promising. I will therefore use the results from these :) 

For CSHNT, these errors come before the "END-of-Interconnect-DETAILS".:
Default config:
RayTracer: intersection_table.cc:170: virtual std::pair<std::vector<MemoryTransactionRecord>, std::vector<MemoryStoreTransactionRecord> > Baseline_warp_intersection_table::add_intersection(uint32_t, uint32_t, uint32_t, uint32_t, const ptx_instruction*, ptx_thread_info*): Assertion `index[tid] < INTERSECTION_TABLE_MAX_LENGTH' failed.

Updated config gives another assertion error:
RayTracer: instructions.cc:7565: void anyhit_exit_impl(const ptx_instruction*, ptx_thread_info*): Assertion `hit_list.size() == n_hits' failed.

You can take a look at my logs: [logs.zip](https://github.com/user-attachments/files/19507504/logs.zip). Note that CAR and ROBOT were OOM-killed, so those can be skipped.

Before reading this thread, I had only three working benchmarks - BUNNY, SHIP and WKND , but with the knowledge that the Assertion `src_bs == dst_bs' failed issue is okay, I have a lot more, which is great. This still does not give the best experience, so I would love some help finding out why I get these issues, If they are not normal. :)
